#!/usr/bin/env node
/**
 * 에이전트 스킬 동기화.
 *
 * 원본은 .agents/skills/ 하나입니다(Codex가 직접 읽음). Claude Code가 읽는 .claude/skills/는
 * 이 스크립트가 만드는 사본이며, 각 SKILL.md에 "직접 고치지 말라"는 안내를 붙입니다.
 *
 *   node scripts/sync-skills.mjs          원본 → 사본 복사, 원본이 사라진 사본 삭제
 *   node scripts/sync-skills.mjs --check  사본이 원본과 다르면 목록을 출력하고 실패(exit 1)
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(root, '.agents/skills');
const target = join(root, '.claude/skills');
const marker = '.generated';
const check = process.argv.includes('--check');

const notice = (name) =>
  `<!-- 생성된 파일: .agents/skills/${name}/ 에서 복사됩니다. 직접 고치지 말고 원본을 고친 뒤 \`npm run sync:skills\`를 실행하세요. -->\n`;

/** SKILL.md는 frontmatter 바로 뒤에 안내를 넣습니다. 다른 파일은 그대로 복사합니다. */
function render(name, file, content) {
  if (file !== 'SKILL.md') return content;
  const end = content.startsWith('---\n') ? content.indexOf('\n---\n', 4) : -1;
  if (end === -1) return notice(name) + content;
  const split = end + '\n---\n'.length;
  return `${content.slice(0, split)}\n${notice(name)}${content.slice(split)}`;
}

function listFiles(dir, base = dir) {
  return readdirSync(dir).flatMap((entry) => {
    if (entry === '.DS_Store') return [];
    const path = join(dir, entry);
    return statSync(path).isDirectory() ? listFiles(path, base) : [relative(base, path)];
  });
}

const skills = readdirSync(source).filter((name) => existsSync(join(source, name, 'SKILL.md')));

/** 사본 폴더 안에 있어야 할 파일과 내용. */
const expected = new Map();
for (const name of skills) {
  for (const file of listFiles(join(source, name))) {
    const content = readFileSync(join(source, name, file), 'utf8');
    expected.set(join(name, file), render(name, file, content));
  }
  expected.set(join(name, marker), 'Generated by scripts/sync-skills.mjs from .agents/skills. Do not edit.\n');
}

/** 이 스크립트가 만든(marker가 있는) 사본만 관리합니다. 손으로 만든 Claude 전용 스킬은 건드리지 않습니다. */
const managed = existsSync(target)
  ? readdirSync(target).filter((name) => existsSync(join(target, name, marker)))
  : [];
const actual = new Map();
for (const name of managed) {
  for (const file of listFiles(join(target, name))) actual.set(join(name, file), readFileSync(join(target, name, file), 'utf8'));
}

const problems = [];
for (const [file, content] of expected) {
  if (!actual.has(file)) problems.push(`missing  .claude/skills/${file}`);
  else if (actual.get(file) !== content) problems.push(`changed  .claude/skills/${file}`);
}
for (const file of actual.keys()) {
  if (!expected.has(file)) problems.push(`extra    .claude/skills/${file}`);
}

if (check) {
  if (problems.length) {
    console.error('스킬 사본이 원본(.agents/skills)과 다릅니다. `npm run sync:skills`를 실행하세요.\n');
    console.error(problems.map((line) => `  ${line}`).join('\n'));
    process.exit(1);
  }
  console.log(`스킬 ${skills.length}개가 동기화되어 있습니다: ${skills.join(', ')}`);
  process.exit(0);
}

// 원본에서 사라진 스킬과 파일을 지운 뒤 다시 씁니다.
for (const name of managed) {
  if (!skills.includes(name)) rmSync(join(target, name), { recursive: true, force: true });
}
for (const file of actual.keys()) {
  if (!expected.has(file)) rmSync(join(target, file), { force: true });
}
for (const [file, content] of expected) {
  const path = join(target, file);
  mkdirSync(dirname(path), { recursive: true });
  if (!existsSync(path) || readFileSync(path, 'utf8') !== content) writeFileSync(path, content);
}
console.log(`스킬 ${skills.length}개를 .claude/skills로 동기화했습니다 (바뀐 파일 ${problems.length}개): ${skills.join(', ')}`);
